### ISSUE TITLE
版本从1.0升级到2.0之后，需要更新哪些方法和注解？

### ISSUE THREAD

**Issue by maxiao124** [dddplus/dddplus#17]
可以出一份，1.0/2.0在使用上不一样的点吗？

比如@DomainAbility注解，在2.0中被废弃，应该使用哪个注解替代；DDD的findAbility方法被废弃，应该使用哪个方法替代？
@funkygao

**Comment by funkygao** [comment]
目前master分支是2.0.0-SNAPSHOT版本，还未正式发布，稍后我发个详细的 2 vs 1 incompatibility list

**Comment by funkygao** [comment]
@maxiao124 
https://github.com/funkygao/cp-ddd-framework/blob/master/doc/for-1.0-users.md

**Comment by maxiao124** [comment]
好的

**Comment by maxiao124** [comment]
> 目前master分支是2.0.0-SNAPSHOT版本，还未正式发布，稍后我发个详细的 2 vs 1 incompatibility list

好的

**Comment by funkygao** [comment]
see https://github.com/funkygao/cp-ddd-framework/releases/tag/2.0.0-SNAPSHOT
