### ISSUE TITLE
DomainArtifacts extensions 不全

### ISSUE THREAD

**Issue by carllhw** [dddplus/dddplus#7]
https://github.com/dddplus/dddplus/blob/166d75c27b9eabc19f9dfce91595160a2972456e/dddplus-runtime/src/main/java/io/github/dddplus/runtime/registry/DomainArtifacts.java#L72-L86

有的拓展只在Partner而Pattern没有实现，这种就不会放到extensions里了

**Comment by funkygao** [comment]
confirmed by adding a test case: https://github.com/funkygao/cp-ddd-framework/commit/54e679f074d64775645063da487efb49778def81

**Comment by funkygao** [comment]
should be ok now

**Comment by funkygao** [comment]
a small refactor: for readability

https://github.com/funkygao/cp-ddd-framework/commit/569540fbb0537361645ad85b71ef04802e281dd9
